### ISSUE TITLE
IEx shell history broken on OTP 28

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#14521]
### Elixir and Erlang/OTP versions

Erlang/OTP 28 [erts-16.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.17.3 (compiled with Erlang/OTP 27)

Same on v1.18 and main. No issues on OTP 27.

### Operating system

macOS

### Current behavior

"Up arrow" correctly shows "erl" history but doesn't seem to save "iex" history:

https://asciinema.org/a/w3iNyQ8jLAALvwKFix85gq4cC

### Expected behavior

IEx history works.

**Comment by josevalim** [comment]
Fixed in Erlang/OTP, thank you!

**Comment by cjfontaine** [comment]
@josevalim I'm currently on Erlang/OTP 28 and Elixir 1.18.4 and shell history still appears to be broken. Did you have to do anything to get it working again?

**Comment by wojtekmach** [comment]
Downgrade to OTP 27 until there's a 28.0.1.

**Comment by cjfontaine** [comment]
> Downgrade to OTP 27 until there's a 28.0.1.

Ah, I was afraid of that. Thank you!

**Comment by josevalim** [comment]
Keeping it open for guidance.

**Comment by Eiji7** [comment]
Temporary fix for `asdf` users:
```bash
asdf install erlang ref:5f3a69d
mv ~/.asdf/installs/erlang/ref-5f3a69d ~/.asdf/installs/erlang/28.0-iex-fix
asdf set erlang 28.0-iex-fix
asdf set elixir 1.19.0-rc.0-otp-28
```

**Comment by wojtekmach** [comment]
OTP-28.0.1 is out and this can be closed. :)
