### ISSUE TITLE
Support --warnings-as-errors on mix test

### ISSUE THREAD

**Issue by perc-MikeBinns** [elixir-lang/elixir#3223]
--warnings-as-errors on mix test would allow automated build systems to catch warnings in test files. Currently, since test files don't get compiled with mix compile, and --warnings-as-errors isn't recognized on mix test, there is no way to root out these warnings in test files via automated builds or linting tools.

**Comment by josevalim** [comment]
@perc-MikeBinns I think this one should be solved with:

    $ MIX_ENV=test mix do compile --warning-as-errors, test

It would be really hard to support all compiler options through `mix test`.

**Comment by nathany** [comment]
I tried running my tests with that command but I still get warnings

```
MIX_ENV=test mix do compile --warning-as-errors, test --exclude remote
```

```
example.ex:23: warning: variable x is unused
```

For now I'm running the following on CI
```
mix compile --warnings-as-errors
mix test --exclude remote
```

**Comment by nathany** [comment]
Sorry, my fault. A warning-as-errors vs. warnings-as-errors typo.

**Comment by is-score** [comment]
This is not working for me, I see the warning that is in the test itself as it runs the test but it just shows everything passed.

**Comment by AdrianSchneider** [comment]
With 

```
elixirc_options: [warnings_as_errors: true]
```

The test compilation fails as expected for me. But, subsequent runs will print the warning but not fail. Given it's not being compiled the second time (without the file changing) it makes sense, but is a little confusing.

**Comment by dylan-chong** [comment]
The problem with `elixirc_options: [warnings_as_errors: true]`  is that you can't say have this enabled on the CI where you want to fail on warnings, but in the local environment it would be very annoying if you had to remove unused aliases and unused variables every time you wanted to run the test

**Comment by whatyouhide** [comment]
@dylan-chong you can do `elixirc_options: [warnings_as_errors: System.get_env("CI") == "true"]` or whatever mechanism you use to detect if you're on CI :)

**Comment by dylan-chong** [comment]
@whatyouhide You are a god :D

**Comment by wojtekmach** [comment]
My favourite option is changing CI config, instead of a single `mix test` invocation I have three:

```
MIX_ENV=test mix deps.compile
MIX_ENV=test mix compile --warnings-as-errors
mix test
```

the advantage is when I need to debug the output tests, I don't have a wall of compilation output in front (most CI neatly group command output per command)

**Comment by dylan-chong** [comment]
@wojtekmach  Doesnt that mean you dont get errors for warnings in test files themselves as `mix compile` only works on `src`, not `test`

**Comment by wojtekmach** [comment]
Right, `mix compile` doesn’t work on test/ so there’s no difference between a single `mix test` and `mix compile —warnings-as-errors && mix test`.

**Comment by dylan-chong** [comment]
With the `elixirc_options: [warnings_as_errors: System.get_env("CI") == "true"]` method, has anyone had issues where errors are raised as warnings the first time you run `CI=true mix test` but then rerunning that command does not produce the error (`even though the unused variable warning is printed`) - something to do with caching?

**Comment by tfwright** [comment]
In order to successfully get CI to fail on warnings triggered inside ex_unit test scripts, I needed to add the following to test_helper.ex in my Phoenix app: `Code.put_compiler_option(:warnings_as_errors, true)`

From https://dashbit.co/blog/tests-with-warnings-as-errors

**Comment by jonleighton** [comment]
I used this:

``` elixir
Code.put_compiler_option(:warnings_as_errors, System.get_env("CI") == "true")
```

According to that blog post, the `--warnings-as-errors` flag will be supported on `mix test` in Elixir 1.12+.

**Comment by x-ji** [comment]
Thanks for pointing to the post. It came at exactly the right time when we're also trying to enforce `warnings_as_errors` in our tests.
