### ISSUE TITLE
excoveralls reports function calls interpolated in second line of <> as uncovered

### ISSUE THREAD

**Issue by KronicDeth** [elixir-lang/elixir#3444]
(Opened in response to @josevalim's [request on elixir-lang-talk](https://groups.google.com/forum/#!topic/elixir-lang-talk/YLED-JWJKyI)

1. `git clone git@github.com:KronicDeth/excoveralls_string_concatenation.git`
2. `cd excoveralls_string_concatenation.git`
3. `mix deps.get`
4. `MIX_ENV=test mix coveralls.detail | less`

# Actual

Calls to `func` are marked as missed (red) when interpolated in second line of a two line string concatenation `<>`:

```elixir
 def call_in_map_value do
    %{
      key: "one " <>
           "#{func}" <>
           "three"
    }
  end

  def call_in_unnested do
    "one " <>
    "#{func}" <>
    "three"
  end
  
  def second_line_interpolation do
    "one " <>
    "#{func}"
  end
```

![screen shot 2015-06-29 at 10 18 50 pm](https://cloud.githubusercontent.com/assets/298259/8423316/e3a840fe-1eac-11e5-8c09-4b13aa9f418f.png)
![screen shot 2015-06-29 at 10 19 01 pm](https://cloud.githubusercontent.com/assets/298259/8423324/e87d8f44-1eac-11e5-8766-32eb95ef4525.png)

# Expected

Calls to `func` are marked as hit (green).

# Other test cases

## Call location

`func` is marked as hit when interpolated in the first line of a two line string concatenation or by itself:

```elixir
  def single_line_interpolation do
    "#{func}"
  end

  def first_line_interpolation do
    "#{func}" <>
    "three"
  end
```

![screen shot 2015-06-29 at 10 19 58 pm](https://cloud.githubusercontent.com/assets/298259/8423332/0a356e86-1ead-11e5-829c-0c89d6218a0f.png)

## Interpolated value

Expressions that are compile time constants, such as `1 + 1`, are marked as hit:

```elixir
  def second_line_constant_interpolation do
    "one " <>
    "#{1 + 1}"
  end
```

![screen shot 2015-06-29 at 10 20 30 pm](https://cloud.githubusercontent.com/assets/298259/8423339/172b493a-1ead-11e5-8572-da1413d97343.png)

**Comment by josevalim** [comment]
Can you please verify this has been fixed in Elixir master?

**Comment by KronicDeth** [comment]
No?

Doing `MIX_ENV=test /Users/luke.imhoff/git/elixir-lang/elixir/bin/mix coveralls.detail` with `/Users/luke.imhoff/git/elixir-lang/elixir` at 6fe76595c1e6a3934addc0a1cb5774b1b6d58fda I still get the uncovered line from my mailing list post:

![screen shot 2015-08-21 at 9 56 20 pm](https://cloud.githubusercontent.com/assets/298259/9422186/81a73050-484f-11e5-93f6-49a54315a10c.png)

Do I have to do something other than run mix with the full path to the elixir-lang/elixir to ensure the development copy is used over the homebrew copy? (Note: I did `make clean test` before running `bin/mix`.)

**Comment by josevalim** [comment]
@KronicDeth No, mix will always use the one in your path. Try this:

    MIX_ENV=test /Users/luke.imhoff/git/elixir-lang/elixir/bin/elixir -S /Users/luke.imhoff/git/elixir-lang/elixir/bin/mix coveralls.detail

And then you will run it with elixir. A good way to check is always by calling "mix -v".

**Comment by KronicDeth** [comment]
`MIX_ENV=test /Users/luke.imhoff/git/elixir-lang/elixir/bin/elixir -S /Users/luke.imhoff/git/elixir-lang/elixir/bin/mix coveralls.detail` worked:

![screen shot 2015-08-22 at 6 41 34 pm](https://cloud.githubusercontent.com/assets/298259/9426306/8121e68a-48fd-11e5-9ec6-7bd360ddc83d.png)

... but only after cleaning and rebuilding the project.  Originally, I had this error:

![screen shot 2015-08-22 at 6 40 30 pm](https://cloud.githubusercontent.com/assets/298259/9426309/9f565078-48fd-11e5-891d-9cb799778c71.png)

After doing `mix clean`, `mix deps.cleans`, `mix deps.get`, and then `MIX_ENV=test /Users/luke.imhoff/git/elixir-lang/elixir/bin/elixir -S /Users/luke.imhoff/git/elixir-lang/elixir/bin/mix coveralls.detail` I got

![screen shot 2015-08-22 at 6 38 21 pm](https://cloud.githubusercontent.com/assets/298259/9426308/95617584-48fd-11e5-99f6-40282e89c69b.png)

I then added some parentheses

```
diff --git a/test/controllers/api/v1/user_controller_test.exs b/test/controllers/api/v1/user_controller_test.exs
index c3b68fe..ffca946 100644
--- a/test/controllers/api/v1/user_controller_test.exs
+++ b/test/controllers/api/v1/user_controller_test.exs
@@ -1143,7 +1143,11 @@ defmodule Metasploit.Pro.Api.V1.UserControllerTest do

             with "other user's id" do
               setup context do
-                Dict.put(context, :other_user, Metasploit.Pro.Repo.insert Forge.user :required, %{admin: true})
+                Dict.put(
+                  context,
+                  :other_user,
+                  Metasploit.Pro.Repo.insert Forge.user(:required, %{admin: true})
+                )
               end

               should "GET /api/v1/users/:id", %{conn: conn, other_user: other_user} do
```

Is it expected that I would have had to recompile when going from 0.17 to master?

**Comment by josevalim** [comment]
> Is it expected that I would have had to recompile when going from 1.0.5 to master?

No. I will work on it. Thanks. :)
