### ISSUE TITLE
compilation error evaluating documentation string

### ISSUE THREAD

**Issue by beardedeagle** [elixir-lang/elixir#8830]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): OTP 21.2.6 & Elixir 1.8.1
* Operating system: Mac OSX Mojave 10.14.3

### Current behavior

Given the following module: https://gist.github.com/beardedeagle/cfb09a576892577df8609a826f11b168

The following error is produced:

```
02:58:15 USER@COMPUTER mnesiac ±|copy-fix ✗|→ mix compile --force
Compiling 5 files (.ex)
warning: variable "table_name" does not exist and is being expanded to "table_name()", please use parentheses to remove the ambiguity or change the variable name
  lib/mnesiac/store.ex:52


== Compilation error in file lib/mnesiac/store.ex ==
** (CompileError) lib/mnesiac/store.ex:52: undefined function table_name/0
    (elixir) src/elixir_bitstring.erl:142: :elixir_bitstring.expand_expr/4
    (elixir) src/elixir_bitstring.erl:27: :elixir_bitstring.expand/8
    (elixir) src/elixir_bitstring.erl:20: :elixir_bitstring.expand/4
    (elixir) expanding macro: Kernel.@/1
```

### Expected behavior

I'd expect this to be a valid document string. I tried pinning table_name, making the logger message a anon func, escaping the `#` and the backticks for the code example. None worked.

**Comment by josevalim** [comment]
Doc strings are regular strings. So you have to disable interpolation by
using the ~S sigil. Using @doc ~S””” should fix it.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by beardedeagle** [comment]
That produces:
```
Compiling 5 files (.ex)
warning: variable "record_name" does not exist and is being expanded to "record_name()", please use parentheses to remove the ambiguity or change the variable name
  test/support/example_store.ex:4

warning: variable "record_name" does not exist and is being expanded to "record_name()", please use parentheses to remove the ambiguity or change the variable name
  test/support/example_store.ex:4

warning: variable "record_name" does not exist and is being expanded to "record_name()", please use parentheses to remove the ambiguity or change the variable name
  test/support/example_store.ex:4


== Compilation error in file test/support/example_store.ex ==
** (CompileError) test/support/example_store.ex:4: undefined function record_name/0
    (elixir) src/elixir_locals.erl:107: :elixir_locals."-ensure_no_undefined_local/3-lc$^0/1-0-"/2
    (elixir) src/elixir_locals.erl:108: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
```

**Comment by beardedeagle** [comment]
For good measure I blew away the _build and deps folder but the error persists

**Comment by OvermindDL1** [comment]
Adding `~S` fixes the table_name part because the interpolation is escaped now.  However, the code itself still has issues.  From the relevant part of your source:
```elixir
  @doc """
  This function is called by mnesiac either when it has no existing data to use or copy and will initialise a table
  ## Default Implementation
  ```elixir
  def init_store do
    :mnesia.create_table(Keyword.get(store_options(), record_name, __MODULE__), store_options())
  end
  ```
  """
  @callback init_store() :: term
```
You see that you are calling `:mnesia.create_table(Keyword.get(store_options(), record_name, __MODULE__), store_options())`, however `record_name` is not defined prior to its use, hence your build failure.  You need to either fix it to a literal, valid binding, function definition, or need to define such a 0-arity function on the test file module itself.  Your test code must be able to compile and run.

**Comment by beardedeagle** [comment]
The code example is a duplicate of the module code which does compile and run if I take out this doc string. I'll take a closer look though.

**Comment by OvermindDL1** [comment]
> The code example is a duplicate of the module code which does compile and run if I take out this doc string. I'll take a closer look though.

Hmm, unless `record_name` is a 0-arity function in the module I wouldn't see it working?  From just the 'contextual information' I'd guess that `:record_name` was intended instead of `record_name` though?

**Comment by beardedeagle** [comment]
Fair dinkum, thanks for the help all.
