### ISSUE TITLE
Path.join unexpected behavior

### ISSUE THREAD

**Issue by SofaKing18** [elixir-lang/elixir#9284]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.9.1 (compiled with Erlang/OTP 20)
* Operating system: Ubuntu 18.04

### Current behavior

```
Path.join("folder1/subfolder2/", "/")           
"folder1/subfolder2/."
```

### Expected behavior
```
Path.join("folder1/subfolder2/", "/")           
"folder1/subfolder2/"
```

Dot, in the end, is weird and unexpected, is this bug? 

Didn't find this behavior in documentation

**Comment by josevalim** [comment]
Yup, it is a bug. :) We should have a special case to handle when the right side is `"/"`. A PR would be welcome!

**Comment by josevalim** [comment]
To be clear, I think the result should be `"folder1/subfolder2"` as join removes trailing slashes.

**Comment by cybrox** [comment]
Do you want to take a stab at this @SofaKing18? Could also look into it.

**Comment by cybrox** [comment]
For the sake of completion, the issue also exists with `join/1`. E.g.

```
Path.join(["/foo", "bar", "/"]) -> "/foo/bar/."
```

**Comment by SofaKing18** [comment]
I would like to make PR, but if @cybrox  want  - go for it :)

**Comment by cybrox** [comment]
@SofaKing18 Ah, feel free to do so then. I'm just trying to pick up issues that the reporter does not PR themselves ;)

@josevalim `Path.join/2` states _The right path will always be expanded to its relative format_, I feel a hint to this behaviour should be added to `Path.join/1` as well. I think the following can be confusing?
```
iex(13)> Path.join(["", "/", "/usr/bin"])
"./usr/bin"

iex(14)> Path.join(["/", "/", "/usr/bin"])
"/./usr/bin"
```

**Comment by josevalim** [comment]
Path.join/1 is implemented on top of Path.join/2 so fixing one should fix the other.

**Comment by cybrox** [comment]
I know. Fixing the reported issue would fix the second example, the first one would still persist, though. Shouldn't an empty list element be ignored instead of making the whole path relative?
